services:
    server:
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
    nginx:
        restart: always
        build:
          dockerfile: Dockerfile
          context: ./controller
        ports:
          - '80:80'
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app           
# mysql:
#   image: mysql:latest
#   ports:
#     - "3306:3306"
#   environment: 
#     - MYSQL_ROOT_PASSWORD=password