#!/bin/bash
sudo apt update -y

sudo apt install awscli -y
sudo apt install nginx -y
sudo systemctl start nginx
sudo systemctl enable nginx
sudo chmod -R 755 /var/www/html
sudo apt install php php7.4-fpm -y
sudo aws s3 cp s3://atymhw3/setupnginx/index.php /var/www/html/index.php
sudo aws s3 cp s3://atymhw3/setupnginx/default /etc/nginx/sites-available/default
sudo rm /var/www/html/index.nginx-debian.html


sudo systemctl restart nginx
sudo apt upgrade -y
